# Generated by Django 4.1.13 on 2024-02-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакцию', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
